In [31]:
import numpy as np
import tensorflow as tf
%load_ext autoreload
%autoreload 2
from train_pg_f18 import *
import math

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [40]:


c = tf.random.categorical(logits = np.ones((5,4)), num_samples =1)
c2 = tf.reshape(c, [-1])
with tf.Session() as sess:
    d = sess.run(c)
    d2 = sess.run(c2)
print(d) 
print(d.shape)
print(d2, d2.shape)

[[2]
 [0]
 [0]
 [2]
 [3]]
(5, 1)
[2 1 0 3 2] (5,)


In [32]:
import gym
env = gym.make('CartPole-v0')
rew_his = []

for i_episode in range(20):
    observation = env.reset()
    rew = 0
    for t in range(100):
        env.render()
        /#print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        rew += reward
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
    rew_his.append(rew)
env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Episode finished after 12 timesteps
Episode finished after 17 timesteps
Episode finished after 11 timesteps
Episode finished after 16 timesteps
Episode finished after 19 timesteps
Episode finished after 45 timesteps
Episode finished after 32 timesteps
Episode finished after 23 timesteps
Episode finished after 15 timesteps
Episode finished after 11 timesteps
Episode finished after 57 timesteps
Episode finished after 15 timesteps
Episode finished after 22 timesteps
Episode finished after 53 timesteps
Episode finished after 31 timesteps
Episode finished after 17 timesteps
Episode finished after 19 timesteps
Episode finished after 18 timesteps
Episode finished after 31 timesteps
Episode finished after 12 timesteps


In [33]:
print(rew_his)
print()
print('mean:', np.mean(rew_his))

[12.0, 17.0, 11.0, 16.0, 19.0, 45.0, 32.0, 23.0, 15.0, 11.0, 57.0, 15.0, 22.0, 53.0, 31.0, 17.0, 19.0, 18.0, 31.0, 12.0]

mean: 23.8


In [2]:
a = []

a.append(np.ones((5,)))
a.append(np.ones((4,)))
a.append(np.ones((6,)))
a.append(np.ones((3,)))

In [15]:
np.hstack((np.ones((5,)), np.ones((4,))))

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
a
for j in a:
    print(j)
    print(np.sum(np.array(j)))
    print(j*np.sum(np.array(j)))

[1. 1. 1. 1. 1.]
5.0
[5. 5. 5. 5. 5.]
[1. 1. 1. 1.]
4.0
[4. 4. 4. 4.]
[1. 1. 1. 1. 1. 1.]
6.0
[6. 6. 6. 6. 6. 6.]
[1. 1. 1.]
3.0
[3. 3. 3.]


In [10]:
np.hstack(a)
len(a)

4

In [27]:
len(np.ones(5,))

5

In [26]:
gamma = 2

np.geomspace(1, 2**4, num=5)

array([ 1.,  2.,  4.,  8., 16.])

In [15]:
a = []

a.append(np.ones((5,)))
a.append(np.ones((4,)))
a.append(np.ones((6,)))
a.append(np.ones((3,)))



In [20]:
np.hstack(a).ravel()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [ ]:
agentt = Agent

In [31]:
# 2-(a), (b) test done - (1), (2) :  test done
tf.reset_default_graph()
input_ph = tf.placeholder(tf.float32, [None, 10])
input_arr = np.random.randn(32,10)
sy_logstd = tf.get_variable('std', shape = 5, dtype=tf.float32)

with tf.Session() as sess:
    out = build_mlp(input_ph, output_size = 5, scope = 'test', n_layers = 2, size = 20)
    var = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, scope= 'test')
    sess.run(tf.global_variables_initializer())    
    out_arr = sess.run([out, var], feed_dict={input_ph:input_arr})
    std = sess.run(sy_logstd)
print(out_arr[0].shape, out_arr[0])
for j in out_arr[1]:
    print(j.shape)
#
print(var)
print(std, std.shape)

(32, 5) [[-4.69931811e-02  1.02999449e-01 -6.29050210e-02 -1.89057946e-01
   8.05720389e-02]
 [ 1.35244250e-01 -9.01301265e-01  1.47474334e-02  6.53059125e-01
  -3.42480600e-01]
 [ 4.88065720e-01 -8.98461491e-02 -2.26276264e-01  2.76843011e-01
   1.57984108e-01]
 [ 1.47151023e-01 -5.61738014e-03  3.48476321e-03  4.31437075e-01
   7.77807891e-01]
 [-1.02003360e+00 -2.31248647e-01 -4.67961729e-02  4.91349578e-01
  -4.78857160e-01]
 [-1.03207076e+00  2.10597262e-01  1.30666882e-01  1.04146965e-01
  -1.91832319e-01]
 [ 5.68055809e-01 -6.98110521e-01 -5.90415120e-01  2.80043721e-01
  -1.20537713e-01]
 [-8.86808634e-02  1.22532964e-01 -1.53636232e-01 -9.14593041e-02
   1.11717892e+00]
 [-1.94952905e-01  3.92291218e-01  7.60088146e-01 -9.76043344e-01
  -2.20442265e-02]
 [ 2.43998304e-01  5.80326438e-01 -4.73160446e-02 -2.32926905e-01
   1.04481839e-01]
 [ 1.86258763e-01 -5.71553349e-01  3.29314023e-01 -3.19563568e-01
   4.43237960e-01]
 [-2.00900346e-01 -2.56709814e-01 -1.42537355e-01  3.8920

In [134]:
# 2-(3): test done
tf.reset_default_graph()
"""
tf.random.normal(
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
"""
#samples = tf.random.categorical(np.ones((6,10)), 1)
#samples2 = tf.reshape(samples, [-1])
z = tf.random.normal(shape=(4,), stddev = np.random.randn(4,))
z2 = tf.expand_dims(z, axis = 0)
mean = np.random.randn(5,4)
with tf.Session() as sess:
    #res = sess.run(samples)
    #print(res)
    
    #res2 = sess.run(samples2)
    #print(res2, res2.shape)
    zz = sess.run(z)
    zz2 = sess.run(z2)
#print(varr)
#res.shape
print('z = ',zz)
print('z2 = ', zz2, zz2.shape)
print('sy_sampled_ac = ', (mean+zz2).shape)
print()
print('mean = ', mean)
print()
print('sy_smapled_ac = ', mean+zz2)

z =  [-0.27874848  0.07826985  1.2372148   1.04118   ]
z2 =  [[0.15438868 0.328141   0.25468242 0.60012186]] (1, 4)
sy_sampled_ac =  (5, 4)

mean =  [[-0.88155433  0.67220327 -2.01542004 -0.39923055]
 [ 1.19103707 -0.15253355  1.00513595 -0.47525845]
 [-1.44814544  0.68849058 -0.65442876  0.70160376]
 [ 0.0191899  -1.057263    0.59087228  0.79974818]
 [-0.80300126 -0.11019391 -0.18371083  0.04181748]]

sy_smapled_ac =  [[-0.72716565  1.00034427 -1.76073762  0.20089131]
 [ 1.34542575  0.17560745  1.25981838  0.12486341]
 [-1.29375676  1.01663158 -0.39974634  1.30172562]
 [ 0.17357858 -0.729122    0.8455547   1.39987003]
 [-0.64861258  0.2179471   0.07097159  0.64193933]]


In [147]:
# pr2 (4), (5)
np.random.seed(5)
inputt = tf.placeholder(tf.float32, [2,5])
ss = np.random.randn(2,5)
print('ss: ', ss)
cc1 = tf.nn.softmax(inputt, axis  =1)
cc = tf.log(cc1+1e-10)
with tf.Session() as sess:
    
    ress = sess.run([cc, cc1], feed_dict={inputt:ss})

print()
print('softmax',ress[1])
print()
print('log prob',ress[0])

ss:  [[ 0.44122749 -0.33087015  2.43077119 -0.25209213  0.10960984]
 [ 1.58248112 -0.9092324  -0.59163666  0.18760323 -0.32986996]]

softmax [[0.10008091 0.04624167 0.7318113  0.05003183 0.07183424]
 [0.62811214 0.0519876  0.07142164 0.15568595 0.09279266]]

log prob [[-2.3017762  -3.073874   -0.3122326  -2.995096   -2.633394  ]
 [-0.46503657 -2.9567502  -2.6391544  -1.8599144  -2.3773878 ]]
